# Use the official Python image as a base image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any dependencies required by your Flask application
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port on which your Flask application will run
EXPOSE 5000

# Specify the command to run your Flask application
CMD ["python", "app.py"]
